### ISSUE TITLE
Scanning a domain on CloudFlare

### ISSUE THREAD

**Issue by drego85** [maurosoria/dirsearch#67] opened 2017-09-07 08:06 UTC
Hello,
this morning I tried scanning 3 domains using the CDN and SSL certificate of CloudFlare . Scanning always reports the same error:

"CONNECTION TIMEOUT: There was a problem in the request to:

Task Completed "

If you want, you can try using my domain to test: https://www.andreadraghetti.it

I think the problem is that Dirsearch makes a Requests request to the domain IP, the domain name is included in the header. But since it's a CDN, the IP does not contain any data off the site.

I tried to modify the Requester.py code as follows:

```

                if self.requestByHostname:
                    url = "{0}://{1}:{2}".format(self.protocol, self.host, self.port)
                else:
                    url = "{0}://{1}:{2}".format(self.protocol, self.host, self.port)

```
and now it works properly.

I do not know why it was decided to scan the IP and not the URL directly. So I avoided doing a Pull Request with code modification.

I leave Mauro the job of intervening, he will know how to work better than me.

Thank you

**Comment by maurosoria** [comment] 2017-09-08 02:05
Have you checked -b/--request-by-hostname argument? 

I decided a long time ago, because the dns resolving overhead. Maybe I should revert that change back. Don't know yet.

**Comment by drego85** [comment] 2017-09-12 08:59
Thanks, I did not see the pull request.

**Comment by dxa4481** [comment] 2017-10-01 04:00
Hey, I can confirm the issues is with making request by IP. CloudFlare will not complete the SSL handshake. I'm not sure how CloudFlare knows the difference, but it would be super helpful if dirsearch could do a quick preflight to check to see if the TLS connection is possible with raw IP requests, before switching to raw IP requests.

**Closed** 2020-08-26 12:15 UTC
