### ISSUE TITLE
New Flag: exclude-sizes-by-limit

### ISSUE THREAD

**Issue by iseries** [maurosoria/dirsearch#1137] opened 2022-07-18 11:02 UTC
### What is the feature?
It would be great to have a flag that works similar to `--exclude-sizes` but specifying a limit instead of defined bytes. E.g. if more than 10 requests return the same number of bytes, skip subsequent requests with the same sizes for the current target. e.g. `--exclude-sizes-by-limit 10`.

### What is the use case?
Sometimes a host response with header 200 instead of 404. In case of one target, we can stop the scan, configure the  `--exclude-sizes` flag and skip them in the next run. But if you have more than 15 targets, its really frustrating and must be monitored all the time.

**Comment by shelld3v** [comment] 2022-07-27 08:04
It's a known issue and I have actually considered a bigger workaround for this

**Comment by shelld3v** [comment] 2022-07-29 17:15
Duplicate of #228

**Closed by shelld3v** 2022-07-29 17:15 UTC
Labels: enhancement
