### ISSUE TITLE
Failed module imports

### ISSUE THREAD

**Issue by gabrielcosi** [maurosoria/dirsearch#518] opened 2020-10-20 23:12 UTC
I'm getting this error:
`File "dirsearch.py", line 28, in <module>
    from lib.core import ArgumentParser
ModuleNotFoundError: No module named 'lib'`
I've tried multiple python versions (3.9,3.8.6,3.6.8) with no results.

**Comment by shelld3v** [comment] 2020-10-21 05:00
Hi, can't reproduce. Can you give me information about the OS, any modified content,... Remember that if you want to run dirsearch with python3, you need to run the following command: `python3 dirsearch.py ...`. And if you are using a third-party app to run dirsearch, then probably the problem came from there!

**Comment by gabrielcosi** [comment] 2020-10-21 06:59
Sure, I'm running it from macOS 10.15.7. First I tried with python3 and got the same error, my default python3 version was 3.9.0 so I thought it wasn't compatible at all. Then I installed pyenv and virtualenv to test with different python versions (already mentioned above) but nothing changed.

**Comment by shelld3v** [comment] 2020-10-21 08:41
As I described above, I believe the problem maybe from how you run this tool. Did you directly enter the command `pythone3 dirsearch.py ...` to run or use a Symlink or use a tool to automate the dirsearch or running this in another tool?

**Comment by gabrielcosi** [comment] 2020-10-21 19:31
![image](https://user-images.githubusercontent.com/44176694/96773224-d2162700-13a9-11eb-85f1-a9a527b76b42.png)

**Comment by shelld3v** [comment] 2020-10-22 05:05
Hey, what does the `pyenv active dirsearch` command do?

**Comment by gabrielcosi** [comment] 2020-10-22 08:10
It's activating a development environment with python 3.6.8, I manage my python versions with pyenv.

**Comment by shelld3v** [comment] 2020-10-22 08:43
I think the problem was there, since no elsewhere it could be. Can you turn off the development environment with dirsearch and then re-run it?

**Comment by 96312** [comment] 2020-10-23 06:18
I kind of get the same problem on VSC. Then I ran the sample command on the terminal (Windows) and it runs but I see no output displayed.

**Comment by shelld3v** [comment] 2020-10-23 06:32
Any screenshot etc. ?

**Comment by dary-winata** [comment] 2020-11-22 04:52
me too, i got same problem on VirtualBox can u help me

**Comment by shelld3v** [comment] 2020-11-22 05:15
Hi, sorry, this is another issue! And #622 will soon fix it! But until now, @maurosoria hasn't merged it yet (maybe he is sleeping =), so you can fix everything by git the fixed repo: `git clone https://github.com/TheBinitGhimire/dirsearch.git`

**Comment by dary-winata** [comment] 2020-11-22 05:32
thank youuu soo much @shelld3v

**Comment by shelld3v** [comment] 2020-12-22 05:26
Hey @gabrielcosi, can you try to run dirsearch with your default python version 3.9.0 (without setting up the `pyenv`)?

**Comment by shelld3v** [comment] 2021-04-30 04:25
Hi, can you guys try re-installing dirsearch then run `pip3 install .`? (Next time, not `python3 dirsearch.py -u ...` but `dirsearch -u ...` anywhere)

**Comment by shelld3v** [comment] 2021-05-17 08:11
Hi @gabrielcosi, some of our users reported that dirsearch only works with python3.8 or higher

**Comment by shelld3v** [comment] 2021-05-17 09:19
@gabrielcosi I am closing this, feel to ask for reopening

**Closed by shelld3v** 2021-05-17 09:19 UTC
Labels: bug, unreproducible

**Comment by zenahmad10** [comment] 2022-12-01 01:55
Hello friend..
I want to use dirsearch and now I'm having trouble after upgrading the version of python I'm using..
is there any solution for this problem..?

thanks in advance
![image](https://user-images.githubusercontent.com/119353484/204947223-2dee1f2e-f73d-4028-8d04-b596f3ddc9fd.png)

**Comment by shelld3v** [comment] 2022-12-01 04:38
@zenahmad10 You are using an old version of dirsearch
