### ISSUE TITLE
--exclude-texts= not working

### ISSUE THREAD

**Issue by Phoenix1112** [maurosoria/dirsearch#251] opened 2020-07-04 20:27 UTC
hello.. i am using this param --exclude-texts=phpMyAdmin . but despite the target site is the phpmyadmin login page, it shows no results. Although phpMyAdmin is in the source code of the target site, it cannot find dirsearch.

**Comment by IslaIDK** [comment] 2020-08-14 20:37
i did pull request for this issue 
till they fix it just go to /lib/core/ArgumentParser.py and go to line 288 and add this 
self.excludeTexts = config.safe_get("general", "exclude-texts", None)

**Comment by shelld3v** [comment] 2020-08-31 14:35
@Phoenix1112 The problem is now resolved, please close this! (Also remember to re-install `dirsearch` to see the fix)

**Closed** 2020-08-31 14:39 UTC
