### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 

### ISSUE THREAD

**Issue by AMJIYU** [maurosoria/dirsearch#928] opened 2021-07-23 10:52 UTC
Traceback (most recent call last):
  File "/dirsearch/lib/controller/controller.py", line 239, in __init__
    self.requester.request("")
  File "/dirsearch/lib/connection/requester.py", line 254, in request
    raise RequestException({"message": error})
lib.connection.request_exception.RequestException: {'message': 'Cannot connect to: 112.48.128.2:80'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dirsearch/lib/controller/controller.py", line 246, in __init__
    raise SkipTargetInterrupt
lib.controller.controller.SkipTargetInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dirsearch.py", line 48, in <module>
    main = Program()
  File "dirsearch.py", line 44, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/dirsearch/lib/controller/controller.py", line 286, in __init__
    self.report.completed = True
AttributeError: 'NoneType' object has no attribute 'completed'

**Comment by shelld3v** [comment] 2021-07-23 11:55
Duplicate of #922

**Comment by shelld3v** [comment] 2021-07-23 11:55
Will be fixed soon

**Closed by shelld3v** 2021-07-23 11:55 UTC
Labels: bug, duplicate
