### ISSUE TITLE
New Suggestion 

### ISSUE THREAD

**Issue by bootyhunt3r** [maurosoria/dirsearch#753] opened 2021-02-10 16:55 UTC
Hello Team , 
So I have a suggestion for the dirsearch , so from my experience , whenever I run run dirsearch on a target and it throws a file greater than 10-15 mbs , the bruteforced directories doesn't work , so can you add a feature to like discard the target if the file exceeds 10 mb ? That would be a really cool feature in my opinion , what do you think ?

**Comment by shelld3v** [comment] 2021-02-11 01:42
Hmmm! Sounds good

**Comment by bootyhunt3r** [comment] 2021-02-11 06:18
Yeah , it would be a really helpful feature.

**Comment by shelld3v** [comment] 2021-02-11 07:26
We love new feature ideas!! Feel free to give us some ;) This seems like a bug rather than a feature request

**Comment by bootyhunt3r** [comment] 2021-02-11 07:36
So , will you be doing something on this thing ? 
Thank you in advance tho.

**Comment by shelld3v** [comment] 2021-02-11 07:58
Of course, this is our job =)

**Comment by bootyhunt3r** [comment] 2021-02-11 11:53
Thanks , and any idea till when this update will be implemented ? Just a rough idea.

**Comment by shelld3v** [comment] 2021-02-11 12:43
Idk, it usually takes a few minutes or an hour, rarely few days. But, it's almost Lunar New Year's Eve right now in my country, I can't fix it right now! I think it will be 3 days after

**Comment by shelld3v** [comment] 2021-02-12 13:42
Hey @bootyhunt3r, did you see any error traceback? If yes, can u pls post it here?

**Comment by bootyhunt3r** [comment] 2021-02-12 14:01
Did you implante this ?

**Comment by shelld3v** [comment] 2021-02-12 14:05
Haven't yet.

**Comment by bootyhunt3r** [comment] 2021-02-12 14:10
No, I have not seen any error ...

**Comment by shelld3v** [comment] 2021-02-12 14:13
It only gets stuck?

**Comment by bootyhunt3r** [comment] 2021-02-12 16:36
Yeah ..it's getting struck sometimes

**Comment by shelld3v** [comment] 2021-02-14 02:51
Hey, I just forgot, you can currently use the `--maximal` flag. I don't know does it work or not, but, why don't give it a try? :)

**Comment by bootyhunt3r** [comment] 2021-02-14 04:07
This is for the stuck issue ?

**Comment by shelld3v** [comment] 2021-02-14 07:12
yeah

**Comment by bootyhunt3r** [comment] 2021-02-16 07:40
Hello bro , I hope you are well !!
Have you started working on that issue ?

**Comment by shelld3v** [comment] 2021-02-16 07:50
Sorry, forgot about that. I'm going to do it now!!

**Comment by bootyhunt3r** [comment] 2021-02-16 07:50
COol !!!

**Comment by shelld3v** [comment] 2021-02-16 07:51
But we also need to do some tests to find the root cause, do you have any website that can cause this stuck?

**Comment by shelld3v** [comment] 2021-02-16 07:52
Can you do some screenshots?

**Comment by shelld3v** [comment] 2021-02-16 07:59
Did the `--maximal` flag work?

**Comment by bootyhunt3r** [comment] 2021-02-16 08:11
I am actually not really sure how to use maximal flag ..can you help ?

**Comment by shelld3v** [comment] 2021-02-16 08:42
`python3 dirsearch.py -e php -u https://example.com --maximal 10000000`

**Comment by bootyhunt3r** [comment] 2021-02-16 13:27
Hey man , i don't know why vut whenever I am using my dirsearch on my vps with the screen , it is automatically getting killed , what could be the reason , any idea ?

**Comment by shelld3v** [comment] 2021-02-16 15:06
You can try to copy terminal output and paste it here!

**Comment by shelld3v** [comment] 2021-02-16 15:07
Hmm, you didn't have that problem before?

**Comment by bootyhunt3r** [comment] 2021-02-16 15:10
No actually, there was no problem earlier,  i don't whether it's the site or what , but am trring with less threads , let's see how it goes with it.

**Comment by bootyhunt3r** [comment] 2021-02-17 10:07
Hey man , 
SO I think it's working good now , I turned down the threads to 50 , now waiting for that update of yours.

**Comment by shelld3v** [comment] 2021-02-17 10:36
Well, I need to reproduce this! An example of a target?

**Comment by bootyhunt3r** [comment] 2021-02-17 11:21
I was testing this on a private programme, but slso on un.org

**Comment by shelld3v** [comment] 2021-02-17 11:23
What is the path cause stuck in **un.org**

**Comment by bootyhunt3r** [comment] 2021-02-18 04:54
Hey sorry for the late reply , seems like it is working good now, no worries.

**Comment by shelld3v** [comment] 2021-02-18 05:29
Close this?

**Comment by bootyhunt3r** [comment] 2021-02-18 05:53
No i think you got somethin wrong , I want the update to like , if the file size exceeds 5 or 10 mb , stop it at 10 mb. You got it ?

**Comment by bootyhunt3r** [comment] 2021-02-18 05:57
The issue that I told you at the beginning

**Comment by shelld3v** [comment] 2021-02-18 06:10
What about that `--maximal` flag? Have you tried it?

**Comment by bootyhunt3r** [comment] 2021-02-18 06:24
I tried but i don't think that works , can you also try that ?

**Comment by shelld3v** [comment] 2021-02-18 14:08
I need the path that will cause the stuck on **un.org** to can reproduce!

**Comment by bootyhunt3r** [comment] 2021-02-22 05:11
Hey sorry for the late reply , my laptop was broken :c 
I am not getting what are you asking , what do you mean by path ?

**Comment by shelld3v** [comment] 2021-02-22 07:43
I mean, there is a path, for example `/download` that when you hit it: `http://un.org/download`, it will return a huge response body, and make dirsearch stuck! If you don't know that path, you can let me know the wordlist you used.

**Comment by bootyhunt3r** [comment] 2021-02-22 09:38
I used your in tool's wordlist , nothing out of anywhere.

**Comment by shelld3v** [comment] 2021-02-22 10:28
Okay, I will check this soon

**Comment by bootyhunt3r** [comment] 2021-02-25 05:54
Hey man , hope you're okay !
Are you looking into the enhancement ? And any idea till when you would be able to give this feature ?

**Comment by shelld3v** [comment] 2021-02-25 06:37
Hey, I was able to reproduce it, but will take time to fix this stuff, remember that I also have my personal life. You can now dirsearch other hosts, until I fix this

**Comment by shelld3v** [comment] 2021-02-25 07:07
Hi there, my debugger shows that there is a connection error, not because of the response size. This is the server problem

**Comment by shelld3v** [comment] 2021-02-27 04:51
Hey, can you check back? I believe that the server is delaying the response, not the response is too huge

**Comment by DarkRed777** [comment] 2021-04-26 10:21
> Hello Team ,
> So I have a suggestion for the dirsearch , so from my experience , whenever I run run dirsearch on a target and it throws a file greater than 10-15 mbs , the bruteforced directories doesn't work , so can you add a feature to like discard the target if the file exceeds 10 mb ? That would be a really cool feature in my opinion , what do you think ?


BTW, in such scenarios you may try HEAD HTTP verb (default is GET). That may help, give a try anyways.
--http-method=HEAD

**Comment by shelld3v** [comment] 2021-05-08 09:22
I am closing this, feel free to ask for re-opening if you believe the issue is still there

**Comment by shelld3v** [comment] 2021-05-25 15:59
Hello @bootyhunt3r, I finally found the solution for this problem. The fix will be merged soon

**Closed** 2021-06-07 22:03 UTC
Labels: Priority: Medium, bug
