### ISSUE TITLE
support system installation or output to ~.dirsearch

### ISSUE THREAD

**Issue by blshkv** [maurosoria/dirsearch#176] opened 2019-10-10 13:38 UTC
Kindly review and accept the following patch:
https://github.com/pentoo/pentoo-overlay/blob/master/net-analyzer/dirsearch/files/add_homedir_support-r1.patch

There is one small improvement need to be done, see:

https://github.com/pentoo/pentoo-overlay/issues/512

**Comment by blshkv** [comment] 2020-12-04 03:23
Please consider accepting the patch.

**Comment by shelld3v** [comment] 2020-12-04 06:36
Hi, I thought it has been done?

**Comment by blshkv** [comment] 2020-12-04 10:35
ok, sorry. I found a different implementation ;-) Haven't tested yet, is my wordlist file was not installed with 0.4.0.
Closing it for now

**Comment by blshkv** [comment] 2020-12-04 10:52
so I have tried the latest version, got this:
```

  _|. _ _  _  _  _ _|_    v0.3.9
 (_||| _) (/_(_|| (_| )

Extensions: php, html, yml | HTTP method: GET | Threads: 20 | Wordlist size: 7479
Traceback (most recent call last):
  File "/usr/share/dirsearch/dirsearch.py", line 46, in <module>
    main = Program()
  File "/usr/share/dirsearch/dirsearch.py", line 42, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/usr/share/dirsearch/lib/controller/Controller.py", line 131, in __init__
    self.setupErrorLogs()
  File "/usr/share/dirsearch/lib/controller/Controller.py", line 305, in setupErrorLogs
    self.errorLog = open(self.errorLogPath, "w")
PermissionError: [Errno 13] Permission denied: '/usr/share/dirsearch/logs/errors-20-12-04_18-47-11.log'
```

**Comment by shelld3v** [comment] 2020-12-04 12:52
Hi, I changed it a long time ago! Don't install dirsearch from https://github.com/maurosoria/dirsearch/releases, if you have git: `git clone https://github.com/maurosoria/dirsearch.git`, otherwise try to install with this link: https://github.com/maurosoria/dirsearch/archive/master.zip. If you want to install git: `sudo apt-get install git` (for Unix OS, not Windows)

**Comment by blshkv** [comment] 2020-12-04 12:57
can you release a fixed version please? I want to push a stable version to Pentoo.

**Comment by shelld3v** [comment] 2020-12-04 13:04
Hi, I and @maurosoria will release it soon! But we need to wait a couple of days before releasing to see if there is any bug in the latest version

**Comment by shelld3v** [comment] 2020-12-04 13:05
I will tell @maurosoria to release it soon!

**Comment by shelld3v** [comment] 2020-12-04 13:11
Oh, I forgot, you can temporarily fix the bug by editing the `default.conf` file (replace `db/dicc.txt` with `/usr/share/dirsearch/db/dicc.txt`) 👍

**Comment by blshkv** [comment] 2020-12-04 13:25
so I tried the latest git, it is not fixed:
```

  _|. _ _  _  _  _ _|_    v0.4.0
 (_||| _) (/_(_|| (_| )

Extensions: php | HTTP method: GET | Threads: 20 | Wordlist size: 8838
Traceback (most recent call last):
  File "/usr/share/dirsearch/dirsearch.py", line 47, in <module>
    main = Program()
  File "/usr/share/dirsearch/dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/usr/share/dirsearch/lib/controller/controller.py", line 147, in __init__
    self.setupErrorLogs()
  File "/usr/share/dirsearch/lib/controller/controller.py", line 313, in setupErrorLogs
    self.errorLog = open(self.errorLogPath, "w")
PermissionError: [Errno 13] Permission denied: '/usr/share/dirsearch/logs/errors-20-12-04_21-23-29.log'

```

**Comment by shelld3v** [comment] 2020-12-04 13:32
Hey, sorry, I didn't read the error message from the first! And from what I am seeing here, the problem didn't come from dirsearch, the root cause is because dirsearch doesn't have permission to write a file to the `/usr/share` folder (there are some folders in the Unix system that require root to can write files). Try: `sudo python3 dirsearch.py -e example.com` instead of `python3 dirsearch.py -u example.com`

**Comment by blshkv** [comment] 2020-12-04 14:57
no sudo please. As the title says, it has to write all output to a local folder, not to a system location.

**Comment by shelld3v** [comment] 2020-12-04 15:20
But you set the location, not me!

**Comment by blshkv** [comment] 2020-12-04 15:51
I'm packaging the tool for Pentoo Linux, users would install it using "sudo". Once installed, the tool should be able to run under current user and write its output a local ~./dirsearch location.  Clear?

**Comment by shelld3v** [comment] 2020-12-05 06:48
I don't know but this change might impact some of our users. Let me look more!

**Comment by blshkv** [comment] 2020-12-05 07:09
It will not. At the same time, welcome to the long list of other tools I reported including many well-known tools such as sqlmap:
https://github.com/pentoo/pentoo-overlay/issues/596

You can have a look at our patch which we provide earlier (and you failed to accept it https://github.com/maurosoria/dirsearch/pull/177) or how other tools has fixed it.

**Comment by blshkv** [comment] 2020-12-05 07:12
Did I forget to mentioned setup.py? Yes, please create it as well.

**Comment by shelld3v** [comment] 2020-12-05 07:20
Hi, I saw many tools refused your requests =) But whatever, I will try my best, to create an option in `default,conf`, allows the user to set the logs, reports, ... location

**Comment by shelld3v** [comment] 2020-12-05 07:32
>Did I forget to mentioned setup.py? Yes, please create it as well.

This's may weird, but I don't know how to create `setup.py` :P Even what, thank you a lot for adding our tool to your Pentoo package 🎉

**Comment by blshkv** [comment] 2020-12-05 07:38
It is actually hard to main the tool in Pentoo. We have adjusted the patch 2 times already to make it with each new version. We have to create an installer because setup.py is missing. The custom installation script will fail at some point too when you change or add files.

Thus, this bug. Please fix it ;-) As I said, please have a look at our issuer tracker, you will find a lot of examples how to solve various cases.

**Comment by shelld3v** [comment] 2020-12-05 07:42
Hi, I found the fix for your situation, already made by @maurosoria a long time ago. Edit the `default.conf` file:
- `save-logs-home` set to `True`
- `autosave-report` set to `False`

**Comment by blshkv** [comment] 2020-12-05 07:44
Thanks, I'll have a look. Yet, the setup.py would help too

**Comment by shelld3v** [comment] 2021-04-21 08:54
Hi, do you need anything else? Or should we close this?

**Comment by blshkv** [comment] 2021-04-21 09:26
Yes, setup.py is still pending

**Comment by shelld3v** [comment] 2021-04-21 10:20
> Yes, setup.py is still pending

I don't know much about `setup.py`! Feel free to submit a PR for it

**Comment by shelld3v** [comment] 2021-04-21 11:06
I was able to create `setup.py`. PR will be submitted soon!

**Closed** 2021-04-22 12:12 UTC

**Comment by blshkv** [comment] 2021-04-28 02:12
ok, I tested and it works fine. Thanks!

**Comment by shelld3v** [comment] 2021-04-28 04:01
Close this?
