### ISSUE TITLE
Dirsearch not working after android update

### ISSUE THREAD

**Issue by vikramn99** [maurosoria/dirsearch#616] opened 2020-11-20 08:13 UTC
Hi, dirsearch is not working after my android upgrade from 9 to 10. At that time my device is in non rooted condition. Now it's in rooted condition.
Is any solution for this ? If available please let me know it.

The logs are here 

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.9/lib-dynload/_multiprocessing.cpython-39.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/dirsearch/dirsearch.py", line 47, in <module>
    main = Program()
  File "/data/data/com.termux/files/home/dirsearch/dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/data/data/com.termux/files/home/dirsearch/lib/controller/controller.py", line 202, in __init__
    self.setupReports(self.requester)
  File "/data/data/com.termux/files/home/dirsearch/lib/controller/controller.py", line 423, in setupReports
    report = PlainTextReport(
  File "/data/data/com.termux/files/home/dirsearch/lib/reports/base_report.py", line 109, in __init__
    self.writeQueue = Queue()
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/context.py", line 103, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/queues.py", line 40, in __init__
    from .synchronize import SEM_VALUE_MAX as maxsize
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

**Comment by shelld3v** [comment] 2020-11-20 08:38
LOL Dirsearch can be run in android? That is mind-blowing for me. This problem probably came from the app that runs our tool, since we don't know about this! Sorry but you need to ask the platform that helps you run PC tools in your phone

**Comment by vikramn99** [comment] 2020-11-20 08:40
Thanks for reply.
The tool previous worked well(with the termux)

**Comment by shelld3v** [comment] 2020-11-20 08:56
From what I saw, the problem came from termux: `/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/synchronize.py`. It said that you missed an implementation, but I don't know what. Please contact and ask termux

**Comment by vikramn99** [comment] 2020-11-20 08:57
Yeah, thanks a lot.

**Comment by shelld3v** [comment] 2020-11-20 09:00
You can close this now! Feel free to reopen whenever you want

**Closed** 2020-11-20 09:01 UTC

**Comment by RupankarGhosh** [comment] 2020-12-01 16:46
@vikramn99 well I'm having the same problem. It's not any problem in dirsearch. The semafore functionality is not implemented in android libc. This problem only happens with dirsearch latest version...
Download the previous version of dirsearch which is v0.3.9 and it'll work just fine. Atleast it's working for me.

**Comment by shelld3v** [comment] 2020-12-03 06:30
Then I'm not an Android expert, I don't know anything about phone, we created this tool just with Python codes, and we are unable to know if any line in those lines made the problem in Android. If you can find the root cause, please tell me and I will fix it! Thanks

**Comment by RupankarGhosh** [comment] 2020-12-05 07:59
@shelld3v the semafore implementation in the newer version causes it to not run in android...but precious versions are running just fine

**Comment by shelld3v** [comment] 2021-01-16 16:18
Hi, sorry for being late! After a google search, I found that the newer version of Android no longer supports multithreading! I can do nothing about this for you guys :(

**Comment by shelld3v** [comment] 2021-01-16 16:23
I think I just said something wrong! See https://github.com/termux/termux-packages/issues/570 for more information!!

**Comment by shelld3v** [comment] 2021-01-16 16:29
>Solution to above problem. Use proot distros in termux. Android support semaphores but the termux being based on aarch64 thats new architecture thee are restrictions. But not on proot based distros as they use arm64 repos l. So install arch or ubuntu on termux

**Comment by vikramn99** [comment] 2021-01-16 17:21
Thanks for information
