### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by hardyfu** [maurosoria/dirsearch#1352] opened 2024-01-03 14:44 UTC
### No output after running

When I run the command "python dirsearch.py -u http://192.168.102.129/pikachu/". the job finished very fast and no output was found both in CLI window and results folder.
![image](https://github.com/maurosoria/dirsearch/assets/58764495/810337de-7065-450b-bda2-1883651b3631)

![image](https://github.com/maurosoria/dirsearch/assets/58764495/1bc694dd-45e7-415e-bc9d-3464f4102b9f)

I have finished "pip install -r requirements.txt".

**Comment by shelld3v** [comment] 2024-01-03 17:09
Duplicate of #1350

**Closed** 2024-01-03 17:24 UTC
Labels: bug
