### ISSUE TITLE
uniq results key

### ISSUE THREAD

**Issue by s0i37** [maurosoria/dirsearch#1368] opened 2024-03-26 15:59 UTC
### What is the feature?

Hello.
Whats about uniqueness results of dirsearch? By len+code.
It's a little tedious to scroll through the same hundreds of rows of results.
Thank you!

### What is the use case?

Real life.

**Comment by nrathaus** [comment] 2024-04-30 07:27
@s0i37 can you provide a better description of what you mean?

Do you mean uniqueness of the finding by the path itself?

The `len` of a path doesn't really mean anything these two paths:
`pathA`
`pathB`

While both have the same length - shouldn't be discarded

**Comment by s0i37** [comment] 2024-05-13 12:54
Here is a good example:
![temp](https://github.com/maurosoria/dirsearch/assets/22872513/1724d145-417b-410d-9a47-324dc9bbd5a6)
It is obvious that the first 16 lines are the same page (same length and code)

**Comment by shelld3v** [comment] 2024-10-24 06:35
Duplicate of #1293

**Closed by shelld3v** 2024-10-24 06:35 UTC
Labels: enhancement
