### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by hu185396** [maurosoria/dirsearch#1031] opened 2022-01-24 06:40 UTC
![image](https://user-images.githubusercontent.com/50415778/150734142-710a1840-2975-4e23-824c-201fa8187806.png)

**Comment by shelld3v** [comment] 2022-01-24 06:43
Hi, can I know the URL?

**Comment by shelld3v** [comment] 2022-01-24 07:04
Duplicate of #1023

**Closed by shelld3v** 2022-01-24 07:04 UTC
Labels: question
