### ISSUE TITLE
Python overwrites some PyPi packages when installing dirsearch with setup.py

### ISSUE THREAD

**Issue by AyOnEs04** [maurosoria/dirsearch#736] opened 2021-01-19 19:47 UTC
I'm having this error when I run it with a non root user, I've tried doing it with `sudo` as well but I had the same error prompt
![dirsearcherror](https://user-images.githubusercontent.com/64980361/105084809-e4653700-5a64-11eb-9395-e83b44ac8edc.jpg)
[dirsearchError.txt](https://github.com/maurosoria/dirsearch/files/5838254/dirsearchError.txt)

```
  File "/opt/dirsearch/dirsearch.py", line 47, in <module>
    main = Program()
  File "/opt/dirsearch/dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/opt/dirsearch/lib/controller/controller.py", line 170, in __init__
    self.setupErrorLogs()
  File "/opt/dirsearch/lib/controller/controller.py", line 337, in setupErrorLogs
    self.errorLog = open(self.errorLogPath, "w")
PermissionError: [Errno 13] Permission denied: '/opt/dirsearch/logs/errors-21-01-19_13-39-11.log'
```
I tried to review the error log but doesn't exist.

**Comment by shelld3v** [comment] 2021-01-30 03:55
Hi, what is the error message when you run with `sudo`? I think you can move your dirsearch to another folder that doesn't require root permission

**Comment by qumusabel** [comment] 2021-02-07 22:10
I think I have the same issue, `Couldn't create the error log. Try running again with highest permission`. The version is 4.1, installed from AUR. I really don't feel like running this with root privileges.

**Comment by shelld3v** [comment] 2021-04-30 04:21
>I really don't feel like running this with root privileges.

You saved dirsearch inside the folder requires root permission so you must run with `sudo`. If you don't want to run as root, move dirsearch folder to somewhere else

**Comment by qumusabel** [comment] 2021-04-30 04:48
> inside the folder requires root permission

But why does it need to save it there? sqlmap doesn't do that, it logs everything to `.local/share/sqlmap/`. There should be at least an option to output to a different directory.

> move dirsearch folder to somewhere else

This is absolutely inconvenient. I want dirsearch in my PATH. And if I install it with pip it saves everything under `site-packages/logs` etc. which is just wrong.

**Comment by shelld3v** [comment] 2021-04-30 05:19
>But why does it need to save it there? sqlmap doesn't do that, it logs everything to .local/share/sqlmap/. There should be at least an option to output to a different directory.

How did you install dirsearch?

>This is absolutely inconvenient. I want dirsearch in my PATH. And if I install it with pip it saves everything under site-packages/logs etc. which is just wrong.

You can try this: https://unix.stackexchange.com/questions/101073/how-to-change-permissions-from-root-user-to-all-users

**Comment by qumusabel** [comment] 2021-04-30 05:35
> How did you install dirsearch?
Via AUR on Arch. This puts it into root-owned directory and writing logs obviously fails. Note that sqlmap is installed in a similar way but works perfectly fine, because it saves everything to my home dir.

> You can try this... 
This is urelated (and also sounds like a really bad practice). `site-packages` is already in my home dir. But dirsearch outputs to `~/.../site-packages/logs` which is wrong.

**Comment by shelld3v** [comment] 2021-04-30 05:51
>Via AUR on Arch. This puts it into root-owned directory and writing logs obviously fails. Note that sqlmap is installed in a similar way but works perfectly fine, because it saves everything to my home dir.

I mean, you installed via git or something? And did you just say that the dirsearch folder is located in the home directory?

>This is urelated (and also sounds like a really bad practice). `site-packages` is already in my home dir

I mean, if the PATH where dirsearch is located requires root permission, you can un-root it (with the link above).

>But dirsearch outputs to `~/.../site-packages/logs which is wrong`.

Seems to be a bug! I will try if can fix this soon

**Comment by qumusabel** [comment] 2021-04-30 06:07
> Seems to be a bug! I will try if can fix this soon

Ideally it should output to `~/.local/share/dirsearch/...`, and to get paths for other systems you can use [appdirs](/ActiveState/appdirs) which would give you the most appropriate path. 
(example:
```py
>>> import appdirs
>>> appdirs.user_data_dir("dirsearch")
<<< '/home/user/.local/share/dirsearch'
```
)


> I mean, you installed via git or something? And did you just say that the dirsearch folder is located in the home directory?
I mean, if the PATH where dirsearch is located requires root permission, you can un-root it (with the link above).

dirsearch itself was located in root-owned directory, and I'm fine with that, as long as it's managed and upgraded by package manager. Un-rooting a system directory is a bad idea in general. 

> But dirsearch outputs to `~/.../site-packages/logs` which is wrong.

This is because you explicitly provide those directories in the repo. Wouldn't it be easier to create them dynamically when you first run dirsearch? That way you can detect the context, i.e.
- If you can't create dirs, fall back to `~/.local/...`
- If dirsearch is run from site-packages, fall back to `~/.local/`
- If dirsearch is run from some directory in `~`, create dirs in that directory

**Comment by shelld3v** [comment] 2021-05-08 13:34
Hey @qumusabel, you can edit `default.conf` and set `save-logs-home` to `True`, as a temporary fix

**Comment by qumusabel** [comment] 2021-05-08 13:51
Ok, thanks.

**Comment by shelld3v** [comment] 2021-05-11 05:19
Hi, fixed in the latest commit. Check `default.conf`, there are options for you

**Comment by qumusabel** [comment] 2021-05-11 14:06
Thanks! 

I think there's a problem, though. `default.conf` will be located in `site-packages`, right? So I would have to edit the python package itself. Could you please make it so that it would try a bunch of config paths (like `~/.config/dirsearch.conf`)? Also `setup.py` still puts `/logs` etc. right into `site-packages/`.

**Comment by shelld3v** [comment] 2021-05-11 14:29
>I think there's a problem, though. default.conf will be located in site-packages, right? So I would have to edit the python package itself

```
git clone dirsearch
cd dirsearch
nano default.conf
pip3 install .
```

>Could you please make it so that it would try a bunch of config paths (like ~/.config/dirsearch.conf)

Will be soon

>Also setup.py still puts /logs etc. right into site-packages/

Yeah, but you can set the location of logs to somewhere else

**Comment by qumusabel** [comment] 2021-05-13 13:52
`db/` ends up as `site-packages/db` too, can you fix that? Sorry for late response

**Comment by shelld3v** [comment] 2021-05-13 14:08
This is a really big problem, not just `db` but also `lib`, `thirdparty`, `default.conf`, ... I will find a solution for this soon

**Comment by shelld3v** [comment] 2021-05-14 07:38
Hi @qumusabel, can you create a better `setup.py`?

**Comment by qumusabel** [comment] 2021-05-14 08:40
Ok, I can try to. 

I've looked at sqlmap's directory structure, and it looks like yours is inspired by it. However, they don't provide `setup.py` in their github repo. But in PyPI the package's structure is this:
```
.
├── MANIFEST.in
├── PKG-INFO
├── README.rst
├── setup.cfg
├── setup.py
├── sqlmap
│   ├── __init__.py (!)
│   ├── README.md
│   ├── sqlmap.py
│   └── ...
└── sqlmap.egg-info
    └── ...
```

And `setup.py` is quite simple:
```py
setuptools.setup(
    ...
    packages=setuptools.find_packages(),
    include_package_data=True,
    ...
)
```

So it definitely looks like they have a separate process to generate PyPI packages.
My ideas on how to implement this flow: make a `build.py`(or some other name) script instead of `setup.py` that would create the necessary directory structure in a temp directory, then invoke a `setup.py` in that directory. Or publish the package (via gh actions).

Does it sound reasonable to you? Please have a look at how they do it yourself: 
https://pypi.org/project/sqlmap/#files.

They also provide `sqlmap/__init__.py` with
```py
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
```
Which promotes all the stuff like `thirdparty` to toplevel import at runtime, without actually putting it into `site-packages/`.

**Comment by qumusabel** [comment] 2021-05-14 09:36
So, I've tried to hack together something that would mimic the sqlmap's installation behavior. When running `setup.py` it would only install `'dirsearch': '../dirsearch'` (path is calculated on runtime). Then something like 
```py
package_data={'dirsearch': ['./**/*' , './default.conf']}
```
should've done the trick, `find_packages('../dirsearch')` won't work either. So probably pre-install package directory structuring is the way to go. 

(Also can't figure out why `__init__.py` I put at toplevel doesn't run...)

**Comment by shelld3v** [comment] 2021-05-14 15:00
>I've looked at sqlmap's directory structure, and it looks like yours is inspired by it

Nope, it was altdns

> So, I've tried to hack together something that would mimic the sqlmap's installation behavior. When running `setup.py` it would only install `'dirsearch': '../dirsearch'` (path is calculated on runtime). Then something like
> 
> ```python
> package_data={'dirsearch': ['./**/*' , './default.conf']}
> ```
> 
> should've done the trick, `find_packages('../dirsearch')` won't work either. So probably pre-install package directory structuring is the way to go.
> 
> (Also can't figure out why `__init__.py` I put at toplevel doesn't run...)

Feel free to submit a PR, I had tested for a better `setup.py` a lot but failed, so this is the result

**Comment by qumusabel** [comment] 2021-05-14 16:24
> Nope, it was altdns

Oh, ok, sorry :)

> I had tested for a better `setup.py` a lot but failed

Yeah, I'm starting to hate it now. I'm working on `install.py` that would create a working environment to correctly install dirsearch. Something like this:
```
 $ python install.py
Copying to /tmp/dirsearch-env-xxxxxx
Running 'pip install . '
``` 
and if it errors out we can just fall back to `setup.py` install. Then you can `cd` into that directory and do other packaging stuff. (maybe have an option to just create the environment). Also, sqlmap's `__init__.py` hack works perfectly. So the main obstacle now should be to write a script that will manage that.

**Comment by shelld3v** [comment] 2021-05-19 14:30
Hi @qumusabel, have you able to do it?

**Comment by qumusabel** [comment] 2021-05-19 14:42
Hi, I'm a bit busy rn, but slowly getting there

**Comment by qumusabel** [comment] 2021-05-19 14:44
Still not sure about `install.py`, thinking of a way to 'forward' setup.py to that new `setup.py` in separate directory.

**Closed** 2021-05-27 05:33 UTC
Labels: Priority: High, bug

**Comment by shelld3v** [comment] 2021-06-08 04:25
Hi @qumusabel, your hack in `setup.py` makes me stuck on uploading the project to [PyPi](https://pypi.org).

I executed this:

```python
python3 setup.py sdist bdist_wheel
```

But I couldn't find the `dist/` folder anywhere

**Comment by qumusabel** [comment] 2021-06-08 04:45
It's all copied to /tmp, but in the end the temp folder is deleted. I think commenting the last line would help.

**Comment by shelld3v** [comment] 2021-06-09 06:47
> It's all copied to /tmp, but in the end the temp folder is deleted. I think commenting the last line would help.

So what should I do now?

**Comment by qumusabel** [comment] 2021-06-09 07:07
When you run `setup.py` it prints where the temp folder is located (`/tmp/dirsearch-instal-xxxxxxxx/`). You can find `dist/` there.

**Comment by shelld3v** [comment] 2021-06-09 07:12
```bash
$ python3 setup.py sdist bdist_wheel
Created setup.py env in /tmp/dirsearch-install-7b_aqu7i
running sdist
running egg_info
...
$ cd /tmp/dirsearch-install-7b_aqu7i
-bash: cd: /tmp/dirsearch-install-7b_aqu7i: No such file or directory
```

**Comment by qumusabel** [comment] 2021-06-09 07:13
Did you comment this line?
![image](https://user-images.githubusercontent.com/18624304/121309819-16940a00-c91c-11eb-9111-aad9f0660714.png)

**Comment by shelld3v** [comment] 2021-06-09 07:40
Published to Pypi, but another issue:

```bash
$ pip3 install dirsearch
Requirement already satisfied: dirsearch in /home/admin/.local/lib/python3.9/site-packages (0.4.1)
Requirement already satisfied: cryptography>=2.8 in /usr/lib/python3/dist-packages (from dirsearch) (3.3.2)
Requirement already satisfied: urllib3>=1.21.1 in /home/admin/.local/lib/python3.9/site-packages (from dirsearch) (1.25.10)
Requirement already satisfied: PySocks in /home/admin/.local/lib/python3.9/site-packages (from dirsearch) (1.7.1)
Requirement already satisfied: chardet>=3.0.2 in /home/admin/.local/lib/python3.9/site-packages (from dirsearch) (3.0.4)
Requirement already satisfied: certifi>=2020.11.8 in /home/admin/.local/lib/python3.9/site-packages (from dirsearch) (2020.12.5)
$ dirsearch -u example.com -e php
Traceback (most recent call last):
  File "/home/admin/.local/bin/dirsearch", line 8, in <module>
    sys.exit(Program())
  File "/home/admin/.local/lib/python3.9/site-packages/dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/home/admin/.local/lib/python3.9/site-packages/lib/controller/controller.py", line 68, in __init__
    open(FileUtils.build_path(script_path, "banner.txt"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/admin/.local/lib/python3.9/site-packages/banner.txt'
```

**Comment by qumusabel** [comment] 2021-06-09 07:47
Wait, your `site-packages` are wrong. Notice where `lib/` ended up. 
I can't reproduce the problem, on my machine it was installed correctly.

`/home/user/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.9/site-packages/*dirsearch*/dirsearch.py`

**Comment by shelld3v** [comment] 2021-06-09 08:11
It works perfectly now

**Comment by shelld3v** [comment] 2022-10-03 12:56
Hi @qumusabel, I can't upload dirsearch to PyPi now, nothing was created under `/tmp` 🤔

**Comment by qumusabel** [comment] 2022-10-03 13:24
Hi. I don't know what went wrong...  I can't investigate it right now, sorry. (Maybe checking dist commands are not in sys.argv before shutil.rmtree will help?)

**Comment by shelld3v** [comment] 2022-10-03 13:36
@qumusabel Sorry for the ping, I solved the issue, couldn't find the output path anywhere in the progress log but found it via `grep`

**Comment by shiva-kurapati** [comment] 2022-10-14 08:28
Hi, I ran dirsearch and this error pops out
![195240405-7c5bbe8c-af1f-4cab-baba-e075ae18e920](https://user-images.githubusercontent.com/77544957/195800132-d5383ff2-cba2-423c-910d-72007a80f436.png)

how can i resolve this error
