### ISSUE TITLE
Missing required dependencies to run

### ISSUE THREAD

**Issue by hu185396** [maurosoria/dirsearch#1186] opened 2022-09-01 03:26 UTC
每次运行都会提示Missing required dependencies to run.Do you want dirsearch to automatically install them?
实际已经安装requirements.txt中的包
![image](https://user-images.githubusercontent.com/50415778/187825361-176d06ab-1dee-4bda-89b4-59ba95494a76.png)

**Comment by shelld3v** [comment] 2022-09-02 07:15
Duplicate of #1135

**Closed by shelld3v** 2022-09-02 07:15 UTC
Labels: bug
