### ISSUE TITLE
TypeError: separation() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by endangalfarisi** [maurosoria/dirsearch#732] opened 2021-01-18 17:49 UTC
### What is the current behavior?

What actually happens?
![Screenshot_6](https://user-images.githubusercontent.com/77636302/104948573-5f015a00-5972-11eb-88c8-eef435dcae1e.png)

### Any additional information?

python 3

#### Checker:
 - [ ] I tested in the latest version of dirsearch

**Comment by yehgdotnet** [comment] 2021-01-18 22:54
@endangalfarisi 

Try
``git reset --hard 18d47e2``

**Comment by shelld3v** [comment] 2021-01-19 04:57
Duplicate of #729

This will be fixed soon!

**Closed** 2021-01-20 01:04 UTC
Labels: bug
