### ISSUE TITLE
Installed in Termux but no output

### ISSUE THREAD

**Issue by euzada** [maurosoria/dirsearch#1191] opened 2022-09-05 18:50 UTC
Hi, I installed dirsearch latest version successfully with no error. All requirements are met. When I run a test using the following example, it shows tasks completed but with no output. No error, no output regardless of the url scanned or parameters used.

`python3 dirsearch.py -u http://target_urrl.com -e php`
I can easily provide screenshot if required. Any suggestions or help will be greatly appreciated. Thanks.

**Comment by shelld3v** [comment] 2022-09-06 03:29
Duplicate of #1190

**Closed by shelld3v** 2022-09-06 03:29 UTC
Labels: bug
