### ISSUE TITLE
failure to recognize "soft blocking"

### ISSUE THREAD

**Issue by Viss** [maurosoria/dirsearch#489] opened 2020-10-14 19:25 UTC
here's an example:
![image](https://user-images.githubusercontent.com/1756255/96035705-4552f280-0e18-11eb-9c5f-ed1babf9630b.png)

this message's headers say 'http 200 ok', and the 'support ID' line is unique every time, so dirsearch doesnt' see this as a failure, and we end up with a mountain of false positives.

**Comment by shelld3v** [comment] 2020-10-15 05:18
Hi, this is a known issue. FYI, dirsearch is able to do that. It sends 2 requests and then compares 2 responses to find the same point between them. Example:

```
Error code: 12345
```

```
Error code: 54321
```
==> Anything that has the "*Error code:*" keyword in the response at the line x after y spaces will be excluded.
But the problem here is this situation:

```
Error code: 12345
```

```
Error code: 13265
```
==> Anything has the form "*Error code: 1xxx5*" will be excluded. And so this response won't be:

```
Error code: 54321
```

There is a way to we can have a better filter, is that dirsearch must send 3-4 requests to has a better cooperation. But this will lead to a problem that dirsearch will have a LONG delay before start brute-forcing, about 3-10 seconds, which will make many users feel angry

**Comment by shelld3v** [comment] 2020-10-15 05:27
We will soon create an option that allows the user to set the calibration level, thank you for your idea 🥇

**Comment by Viss** [comment] 2020-10-15 07:33
In personally have zero problem with a short startup delay - my use of dirsearch usually takes hours. I suppose making a command line argument to turn on aggressive error testing may be super handy!

**Comment by shelld3v** [comment] 2020-10-15 08:36
Yea, but it's only you (and me also)! I know many people will feel not good about that delay. Now it already has a 2-3 seconds delay, so I don't want more

**Comment by shelld3v** [comment] 2021-04-14 13:09
Hello @Viss,

I just released a new feature that allows you to perform calibration on a specified page. This is not the best solution for your problem (the "calibration depth level" is the best feature to fix this problem, which will be implemented on dirsearch soon 👌), but still can be used to help you in this situation. The feature I talked about is `--exclude-content`, by adding this argument into your command: `... --exclude-content random.html`, dirsearch will perform 3 calibration tests (2 default, 1 from *--exclude-content*). Can you try this to see if it works?

**Comment by shelld3v** [comment] 2021-05-17 15:06
Hi @Viss, can you give me the source code of the 

> here's an example:
> ![image](https://user-images.githubusercontent.com/1756255/96035705-4552f280-0e18-11eb-9c5f-ed1babf9630b.png)
> 
> this message's headers say 'http 200 ok', and the 'support ID' line is unique every time, so dirsearch doesnt' see this as a failure, and we end up with a mountain of false positives.

Hi, do you have any website like this for me to do testing?

**Comment by Viss** [comment] 2021-06-11 18:30
sorry for the horrible delay.
Here's a website that exhibits one version of this issue: hidratespark.com
It will return 200 ok responses for stuff that isnt there.
I'm pouring through old reports to try and find this exact issue, and I'll reply again when I have an example domain or two where it will produce this exact bug.

**Comment by shelld3v** [comment] 2021-06-12 05:30
> sorry for the horrible delay.
> Here's a website that exhibits one version of this issue: hidratespark.com
> It will return 200 ok responses for stuff that isnt there.
> I'm pouring through old reports to try and find this exact issue, and I'll reply again when I have an example domain or two where it will produce this exact bug.

I can't reproduce it:

```
$ ./dirsearch.py -u https://hidratespark.com -e php -t 10

  _|. _ _  _  _  _ _|_    v0.4.1
 (_||| _) (/_(_|| (_| )

Extensions: php | HTTP method: GET | Threads: 10 | Wordlist size: 8920

Output File: /tmp/dirsearch/reports/hidratespark.com/_21-06-12_12-27-30.txt

Error Log: /tmp/dirsearch/logs/errors-21-06-12_12-27-30.log

Target: https://hidratespark.com/

[12:27:31] Starting:

Task Completed
```

**Comment by Viss** [comment] 2021-06-12 16:54
if you're testing with the new version, which has the fix I've asked for built in, its likely you arent able to reproduce it because the bug has been fixed. You might want to try with 0.4.0 to see if you can reproduce the bug, because thats the version that had the bug you're trying to reproduce.

**Comment by shelld3v** [comment] 2021-06-13 05:14
Thanks for your feedback, that's good news! I'm closing this now

**Closed by shelld3v** 2021-06-13 05:14 UTC
Labels: Priority: High, enhancement
