### ISSUE TITLE
While running dirsearch I'm getting these errors

### ISSUE THREAD

**Issue by harry1080** [maurosoria/dirsearch#654] opened 2020-12-07 07:42 UTC
### What is the current behavior?
During handling of the above exception, another exception occurred:
urllib3.exceptions.DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))

![image](https://user-images.githubusercontent.com/19358692/101322714-74c72e00-38a2-11eb-8bca-6580813e886f.png)

### What is the expected behavior?

It used to be normal before. This problem has occurred since I updated it with git a few days ago

**Comment by shelld3v** [comment] 2020-12-07 08:43
The problem happens with some Yahoo servers, and we have already known it but still unable to fix it. We are trying to find the fix but we haven't seen a way to stop `requests` from decoding the body yet. It looks like some Yahoo servers return the `content-encoding: gzip` header but with a normal body, which is really weird and I think probably they do this to prevent our tool. 

This is a duplicate of #106

**Comment by shelld3v** [comment] 2020-12-27 04:29
Hey, this is going to be fixed soon ;)

**Comment by harry1080** [comment] 2020-12-28 01:57
> Hey, this is going to be fixed soon ;)

ok,

**Closed** 2020-12-29 02:54 UTC
Labels: bug, duplicate
