### ISSUE TITLE
SSL Error connecting to server. Try the -b flag to connect by hostname

### ISSUE THREAD

**Issue by mikely22** [maurosoria/dirsearch#263] opened 2020-08-05 23:55 UTC
SSL Error connecting to server. Try the -b flag to connect by hostname

Please can you explain me to what way to fix this issue Thanks

**Comment by shelld3v** [comment] 2020-08-31 15:03
Add the -b flag and then close this issue 🌝

**Comment by maurosoria** [comment] 2020-09-14 21:28
I should scan the server for a WAF to do this. The problem is that requests does not cache the DNS by default, and that impacts the performance.

**Comment by shelld3v** [comment] 2021-04-11 12:23
Hi @mikely22, can you retest with the latest commit of dirsearch?

**Closed** 2021-05-03 04:47 UTC
Labels: enhancement
