### ISSUE TITLE
"The wordlist does not exist" when I run dirsearch

### ISSUE THREAD

**Issue by S0ykot** [maurosoria/dirsearch#1018] opened 2022-01-16 11:32 UTC
After running dirsearch, it shows me that "The wordlist does not exist". I am using the latest one.

![Screenshot_4](https://user-images.githubusercontent.com/10108591/149658108-2f6e2973-81dc-4266-9325-d13de34af142.png)

**Comment by shelld3v** [comment] 2022-01-16 12:53
Duplicate of #1016

**Closed by shelld3v** 2022-01-16 12:53 UTC
Labels: bug
