### ISSUE TITLE
Error when running dirsearch

### ISSUE THREAD

**Issue by novanazizr** [maurosoria/dirsearch#730] opened 2021-01-18 05:56 UTC
### What is the question?
When i running dirsearch, its returning an error

What do you like to ask about?
How to fix it

### Any additional information?

Kali Linux 2020.4, dirsearch:v0.4.1, Python 2.7.18, 

### Input command :

python3 dirsearch.py -e php,html,js -u http://mytarget.com

### Output :

Traceback (most recent call last):
  File "/home/cold/Priv8Tools/dirsearch/dirsearch.py", line 47, in <module>
    main = Program()
  File "/home/cold/Priv8Tools/dirsearch/dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/home/cold/Priv8Tools/dirsearch/lib/controller/controller.py", line 169, in __init__
    self.printConfig()
  File "/home/cold/Priv8Tools/dirsearch/lib/controller/controller.py", line 272, in printConfig
    self.output.config(
  File "/home/cold/Priv8Tools/dirsearch/lib/output/cli_output.py", line 217, in config
    config += self.separation(config, particle) + particle
TypeError: separation() takes 2 positional arguments but 3 were given

### Screenshot
https://www59.zippyshare.com/v/Hgqw54fL/file.html

#### Checker:
 - [Yes] I read the documentation (README)

**Comment by dungpx196** [comment] 2021-01-18 06:17
Error might be from new merge. Try lastest tag before new master branch is ok
git checkout v0.4.1

**Comment by shelld3v** [comment] 2021-01-18 06:55
Hi, this has been addressed and will be fixed soon!

**Comment by tomasz-kusy** [comment] 2021-01-18 08:08
Duplicate of #729

**Closed** 2021-01-20 01:04 UTC
Labels: question
