### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip' - Believed to be related to multi-level subdomain

### ISSUE THREAD

**Issue by Horridge** [maurosoria/dirsearch#1023] opened 2022-01-17 11:16 UTC
### What is the current behavior?
Receiving an exception error when attempting to use a multi-level subdomain (the URL in question also includes hyphens, if that's relevant to the issue), e.g. https://level-2.level-1.root-domain.net
An error is not being observed if I try https://level-1.root-domain.net

### What is the expected behavior?
It's expected that disearch would support multiple levels of subdomains. 

### Any additional information?
```
Traceback (most recent call last):
  File "/home/user/dirsearch/lib/controller/controller.py", line 198, in __init__
    self.requester.request("")
  File "/home/user/dirsearch/lib/connection/requester.py", line 287, in request
    raise RequestException({"message": err_msg})
lib.connection.request_exception.RequestException: {'message': None}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dirsearch.py", line 45, in <module>
    main = Program()
  File "dirsearch.py", line 41, in __init__
    self.controller = Controller(self.arguments, self.output)
  File "/home/user/dirsearch/lib/controller/controller.py", line 204, in __init__
    self.output.error(e.args[0]["message"])
  File "/home/user/dirsearch/lib/output/verbose_output.py", line 167, in error
    stripped = reason.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

#### Checker:
[✓] I tested in the latest version of dirsearch (v0.4.2)

**Comment by shelld3v** [comment] 2022-01-17 11:58
Hi, is it possible for me to get the target URL you tried?

**Comment by simonlee-hello** [comment] 2022-01-21 06:35
same problems too.

**Comment by simonlee-hello** [comment] 2022-01-21 06:53
修改/lib/connection/requester.py文件第193行，将err_msg=None，改为err_msg=''即可

**Comment by shelld3v** [comment] 2022-01-23 06:04
Hi can you recheck the issue now?

**Comment by jokerJQ** [comment] 2022-01-23 08:37
Hi, the problem is the URL. Maybe you can change the URL, or the website has WAF

**Comment by shelld3v** [comment] 2022-01-23 10:02
@jokerJQ Do you have an example URL for this?

**Comment by jokerJQ** [comment] 2022-01-23 10:26
![image](https://user-images.githubusercontent.com/59128258/150674211-908f679d-4e08-4770-8457-8d96d965e802.png)
”www.moonlab.com“ This website is on strong WAF ”安全狗“

**Comment by shelld3v** [comment] 2022-01-23 11:49
It seems that the issue was fixed in the latest commit :D Please re-install your dirsearch
![Screenshot from 2022-01-23 18-48-13](https://user-images.githubusercontent.com/59408894/150676939-9d195037-ae82-41f5-af11-7788d799c1b3.png)

**Comment by shelld3v** [comment] 2022-01-24 07:23
@Horridge @jokerJQ @simonlee-hello can you still reproduce this bug?

**Comment by shelld3v** [comment] 2022-03-07 15:03
The bug has been fixed

**Closed by shelld3v** 2022-03-07 15:03 UTC
Labels: bug, unreproducible, Priority: Critical, investigating
